=== rivetlogic/acir/acir/src/main/resources/query.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://acir.rivetlogic.org/QuerySchema"  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://acir.rivetlogic.org/QuerySchema" elementFormDefault="qualified" version="1.0">
	<xs:element name="extract-requests">
		<xs:complexType>
			<xs:sequence>
                <xs:element name="extracts-id" type="xs:string" minOccurs="0" maxOccurs="1" />
                <!-- indicates whether there should be an ack file for no results or not - default is true -->
                <xs:element name="ack-file-for-no-results" type="xs:boolean" minOccurs="0" maxOccurs="1" /> 
                <xs:element ref="definitions" minOccurs="1" maxOccurs="1" />
                <xs:element ref="extract-request" minOccurs="1" maxOccurs="unbounded" />
           </xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dependency-resolver-definitions" minOccurs="0" maxOccurs="1" />
				<xs:element ref="filter-definitions" minOccurs="0" maxOccurs="1" />
				<xs:element ref="transformer-definitions" minOccurs="0" maxOccurs="1" />
				<xs:choice>
					<xs:element ref="deployer-definitions" minOccurs="1" maxOccurs="1" />
					<xs:element ref="undeployer-definitions" minOccurs="1" maxOccurs="1" />
				</xs:choice>
				<xs:element ref="notifier-definitions" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="extract-request">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="store-ref" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
				<xs:element ref="queries" minOccurs="1" maxOccurs="1" />
				<xs:element ref="dependency-resolvers" minOccurs="0" maxOccurs="1" />
				<xs:element ref="filters" minOccurs="0" maxOccurs="1" />
				<xs:element ref="transformers" minOccurs="0" maxOccurs="1" />
				<xs:choice>
					<xs:element ref="deployers" minOccurs="1" maxOccurs="1" />
					<xs:element ref="undeployers" minOccurs="1" maxOccurs="1" />
				</xs:choice>
				<xs:element ref="notifiers" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    
    <xs:element name="property">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- START: deployer related definitions -->
	<xs:element name="deployer">
        <xs:complexType>
            <xs:attribute name="ref" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    
	<xs:element name="deployers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployer" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="deployer-definition">
		<xs:complexType>
            <xs:sequence>
                <xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="deployer-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="deployer-definition" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- END: deployer related definitions -->
	
	
	<!-- START: undeployer related definitions -->
	<xs:element name="undeployer">
        <xs:complexType>
            <xs:attribute name="ref" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    
	<xs:element name="undeployers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="undeployer" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="undeployer-definition">
		<xs:complexType>
            <xs:sequence>
                <xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="undeployer-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="undeployer-definition" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- END: undeployer related definitions -->
	
	<!-- START: notifier related definitions -->
	<xs:element name="notifier">
        <xs:complexType>
            <xs:attribute name="ref" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    
	<xs:element name="notifiers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="notifier" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="notifier-definition">
		<xs:complexType>
            <xs:sequence>
                <xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="notifier-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="notifier-definition" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- END: notifier related definitions -->
	
	<!-- START: transformer related definitions -->
	<xs:element name="transformer-definition">
		<xs:complexType>
            <xs:sequence>
                <xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	
	<xs:element name="transformer-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="content-transformer-definitions" minOccurs="0" maxOccurs="1" />
				<xs:element ref="file-name-transformer-definitions" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="file-name-transformer-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transformer-definition" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="content-transformer-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transformer-definition" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="file-name-transformers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transformer" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="content-transformers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transformer" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="transformer">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="transformers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="content-transformers" minOccurs="0" maxOccurs="1" />
				<xs:element ref="file-name-transformers" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- END: transformer related definitions -->
	
	<!-- START: filter related definitions -->
	<xs:element name="filter-definition">
		<xs:complexType>
            <xs:sequence>
                <xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="filter-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filter-definition" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="filter">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="filters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- END: filter related definitions -->
	
	<!-- START: dependency resolver related definitions -->
	<xs:element name="dependency-resolver-definition">
		<xs:complexType>
            <xs:sequence>
                <xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required" />
			<xs:attribute name="id" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="dependency-resolver-definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dependency-resolver-definition" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="dependency-resolver">
		<xs:complexType>
			<xs:attribute name="ref" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="dependency-resolvers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="dependency-resolver" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- END: dependency resolver related definitions -->
	
	<xs:element name="queries">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="query" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rivetlogic/acir/acir/src/main/resources/samples/sample_query.xml
<?xml version="1.0" encoding="UTF-8"?>
<extract-requests xmlns="http://acir.rivetlogic.org/QuerySchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="query.xsd">
    <extracts-id>id123</extracts-id>
    <!-- should be true/false, default is true
         useful when queries are constantly being polled -->
    <ack-file-for-no-results>false</ack-file-for-no-results>  
	<definitions>
	
			
		<dependency-resolver-definitions>
			<dependency-resolver-definition
				class="org.rivetlogic.export.dependencyresolvers.EmptyDependencyResolver"
				id="empty_dependency_resolver" />
		</dependency-resolver-definitions>
		
		<filter-definitions>
				<filter-definition class="org.rivetlogic.export.filters.DateTimeFilter" id="date_time_filter">
					<properties>
						<property name="olderThan">2010-01-01T00:00:00</property>
						<property name="newerThan">2008-01-01T00:00:00</property>
					</properties>
				</filter-definition>
		</filter-definitions>
		
		<transformer-definitions>
		
			<content-transformer-definitions>
				<transformer-definition class="org.rivetlogic.export.transformers.content.NullContentTransformer"
				                        id="dummy_content_transformer_1"></transformer-definition>
				<transformer-definition class="org.rivetlogic.export.transformers.content.NullContentTransformer"
				                        id="dummy_content_transformer_2"></transformer-definition>
				<!-- 
					this is an example of what a DRM removing transformer would look like.
					
				<transformer-definition class="org.rivetlogic.components.export.transformers.RemoveDRMTransformer" id="remove_drm_transformer">
				   <properties>
				       <property name="password">R3sdTde2d%a</property>
				   </properties>
				</transformer-definition>
				-->
			</content-transformer-definitions>

			<file-name-transformer-definitions>
				<transformer-definition class="org.rivetlogic.export.transformers.filename.ReplaceFirstTransformer" id="normalize_path_transformer">
                    <!-- 
                       this transformer will transform a file name from:
                            /company_home/hbp/products/Higher Ed/130/2008/108038/108038-PDF-ENG/ancillary/some_files2.txt
                       to: 
                            108038/108038-PDF-ENG/some_files2.txt
                     -->
					<properties>
						<property name="targetRegex">/company_home/hbp/products/[^/]+/[^/]+/[^/]+/([^/]+/[^/]+/)([^/]+/)+</property>
						<property name="replacement">$1</property>
					</properties>
				</transformer-definition>

				<transformer-definition class="org.rivetlogic.export.transformers.filename.ReplaceFirstTransformer" id="dummy_filename_transformer">
				    <!-- this transformer replaces 'a' with 'a', essentially doing nothing -->
					<properties>
						<property name="targetRegex">a</property>
						<property name="replacement">a</property>
					</properties>
				</transformer-definition>
			</file-name-transformer-definitions>
		</transformer-definitions>

		<deployer-definitions>
			<deployer-definition class="org.rivetlogic.export.deployers.LocalDeployer" id="local_deployer_1">
				<properties>
					<property name="deployTo">/opt/clients/rivet/acir-upgrades/4.1.2/acir-4.1.2-E-0/queries/export/</property>
				</properties>
			</deployer-definition>
			<!--
			this is an example of an FTP based deployer. 
			<deployer-definition class="org.rivetlogic.components.export.deployers.FtpDeployer" id="ftp_deployer_destination.com">
			    <properties>
	                <property name="deployTo">ftp://ftp.destination.com/hbr/articles/</property>
	                <property name="username">gooduser</property>
	                <property name="password">passwd</property>
			    </properties>
			</deployer-definition>
			-->
		</deployer-definitions>
		
		<notifier-definitions>
			<notifier-definition
				class="org.rivetlogic.export.notifiers.NullCMSNotifier" id="dummy_cms_notifier" />
		</notifier-definitions>
		
	</definitions>

    <extract-request>
    	<store-ref>workspace://SpacesStore</store-ref>
	    <!--
	    this query extract searches for s2 _and_ p2 files in availability 108038-PDF-ENG, 
	    execute dummy_transformer_1 against the resulting content, 
	    execute normalize_path_transformer and dummy_filename_transformer, and
	    deploy the files using local_deployer_1
	    
	    note: 
	       Due to XPATH standard limitations products and availabilities that start with a number need to be escaped as follows:
	           digit  |  escaped-digit
	           _______________________
                 1    |  _x0031_
                 2    |  _x0032_
                 ............
                 9    |  _x0039_
	    -->
		<queries>
            <!-- the query line below searches for files which have a name pattern "*s2.pdf" 
                    that are of type "content"(not a folder), that reside off of folder "output" in the availability "108038-PDF-ENG"
            -->
			<query>@cm\:name:"*.pdf" AND TYPE:"cm:content"</query>
		</queries>
		<transformers>
			<content-transformers>
				<transformer ref="dummy_content_transformer_1" />
			</content-transformers>
			<file-name-transformers>
				<transformer ref="normalize_path_transformer" />
				<transformer ref="dummy_filename_transformer" />
			</file-name-transformers>
		</transformers>
		<deployers>
			<deployer ref="local_deployer_1" />
		</deployers>
	</extract-request>

	<extract-request>
		<store-ref>workspace://SpacesStore</store-ref>
		<queries>
			<query>@cm\:name:"*xml" AND TYPE:"cm:content" AND @cm\:modified:[2008\-08\-16T00:00:00 TO 2012\-09\-10T00:00:00]</query>
		</queries>
		<dependency-resolvers>
			<dependency-resolver ref="empty_dependency_resolver" />
		</dependency-resolvers>
		<!-- <filters>
			<filter ref="date_time_filter" />
		</filters> -->
		<transformers>
			<content-transformers>
				<transformer ref="dummy_content_transformer_2" />
			</content-transformers>
			<file-name-transformers>
				<transformer ref="dummy_filename_transformer" />
			</file-name-transformers>
		</transformers>
		<deployers>
			<deployer ref="local_deployer_1" />
		</deployers>
		<notifiers>
			<notifier ref="dummy_cms_notifier" />
		</notifiers>
	</extract-request>

</extract-requests>
